# .github/workflows/publish.yml
name: Generate a build and push to another branch

on:
  workflow_dispatch:
  push:
    branches:
      - main
  # schedule:
  #   - cron:  '*/30 * * * *' # reenable this when adding dynamic content

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Pulls submodules
        run: git submodule update --init --recursive

      - name: make and get into projects folder
        run: mkdir public/projects


      - name: get GDSC-Website-List-Movie
        run: |
          REPO=GDSC-Website-List-Movie
          cd public/projects
          wget https://codeload.github.com/misaalanshori/$REPO/zip/refs/heads/master
          unzip master
          mv $REPO-master $REPO
          rm master

      - name: 'DEBUG: ls public projects'
        run: ls public/projects
      
      - name: 'DEBUG: ls public projects *'
        run: ls public/projects/*


      - name: get node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run buildstatic # The build command of your project
        
      - name: touching .nojekyll
        run: touch out/.nojekyll
      
      - name: 'DEBUG: ls out'
        run: ls out

      - name: 'DEBUG: ls out/projects'
        run: ls out/projects

      - name: 'DEBUG: ls out/projects/*'
        run: 'ls out/projects/*'

      - name: checkout the other branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ghpg

      - name: push to the other branch
        run: |
          ls $GITHUB_WORKSPACE/ghpg
          echo ================
          rm $GITHUB_WORKSPACE/ghpg/* -r
          rm $GITHUB_WORKSPACE/ghpg/.* || true
          rm $GITHUB_WORKSPACE/ghpg/.github || true
          echo ================
          ls $GITHUB_WORKSPACE/ghpg
          cd $GITHUB_WORKSPACE/ghpg
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "clean up"
          git push
          echo ================
          ls $GITHUB_WORKSPACE/ghpg
          cp $GITHUB_WORKSPACE/out/* $GITHUB_WORKSPACE/ghpg -r
          cd $GITHUB_WORKSPACE/ghpg
          git add .
          git commit -m "generated from commit: $(cd $GITHUB_WORKSPACE; git rev-parse HEAD)"
          git push