# .github/workflows/publish.yml
name: Generate a build and push to another branch

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
      - cron: '43 */6 * * *' # every 6hr (+43min)
    # - cron: '43 */2 * * *' # every 2hr (+43min)
    # - cron:  '*/30 * * * *' # every 30 mins

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Pulls submodules
        run: git submodule update --init --recursive

      - name: get GDSC-Website-List-Movie
        run: |
          REPO=GDSC-Website-List-Movie
          cd public/projects
          wget https://codeload.github.com/misaalanshori/$REPO/zip/refs/heads/master
          unzip master
          mv $REPO-master $REPO
          rm master

      

      - name: get node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run buildstatic # The build command of your project

      - name: fix 404
        run: |
          mv out/404/index.html out/404.html
          rm out/404 -r
        
      - name: touching .nojekyll
        run: touch out/.nojekyll

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages # The branch name where you want to push the assets
          FOLDER: out # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message